name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy_user:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container: riobener/user-service:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: CURL
        run: curl http://localhost:8081/users/health
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pytest
        run: pip install pytest
      - name: Install requests
        run: pip install requests
      - name: Run tests
        run: pytest

      #Push image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push riobener/user-service:latest
